---
apiVersion: v1
kind: Service
metadata:
  name: bodhi
spec:
  type: NodePort
  selector:
    app: bodhi-user-service
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: bodhi-user-service
spec:
  selector:
    matchLabels:
      app: bodhi-user-service
  replicas: 5
  template:
    metadata:
      labels:
        app: bodhi-user-service
    spec:
      containers:
      - name: bodhi-user-service
        image: coderubble/bodhi_user_service:latest
        env:
        -    
          name: JWT_PRIVATE_KEY
          value: myprivatekey
        -    
          name: USER_SERVICE_PORT
          value: "3000"
        -    
          name: SALT
          value: "10"
        -    
          name: POSTGRES_USER
          value: gitlab
        -    
          name: POSTGRES_PASSWORD
          value: gitlabhq_production
        -    
          name: POSTGRES_DB
          value: gitlab
        -    
          name: POSTGRES_HOST
          value: postgresql
        -
          name: API_PREFIX
          value: "/api/v1"
        -    
          name: VERSION
          value: "1.0.0"
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: ".50"
            memory: "100Mi"
          requests:
            cpu: ".50"
            memory: "100Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    run: postgresql
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: gitlab
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: gitlab 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: postgreSQL
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: gitlab
            - name: POSTGRES_DB
              value: gitlabhq_production
            - name: POSTGRES_PASSWORD
              value: gitlab
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: gitlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-pv
spec:
  capacity:
    storage: 1Mi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /bodhi_user_db/sql/
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - example-node