apiVersion: v1
kind: Service
metadata:
  name: bodhi-service
spec:
  type: NodePort
  selector:
    app: bodhi-service-deployment
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 32000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bodhi-service-deployment
  labels:
    app: bodhi-service-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: bodhi-service-deployment 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bodhi-service-deployment
    spec:
      containers:
        - image: coderubble/bodhi_user_service
          name: bodhi-service-deployment
          ports:
            - containerPort: 3000    
          env:
            - name: JWT_PRIVATE_KEY
              value: myprivatekey
            - name: PORT
              value: "3000"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
            - name: POSTGRES_DB
              value: bodhi
            - name: POSTGRES_HOST
              value: bodhi-main-db-service
            - name: SALT
              value: "10"
            - name: API_PREFIX
              value: "/api/v1"
            - name: VERSION
              value: "1.0.0"
            - name: NODE_ENV
              value: dev
---
apiVersion: v1
kind: Service
metadata:
  name: bodhi-main-db-service
spec:
  selector:
    app: bodhi-main-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  labels:
    app: bodhi-main-db
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: bodhi-main-db 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: bodhi-main-db
    spec:
      containers:
        - image: postgres:9.6.2-alpine
          name: postgresql
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: bodhi
            - name: POSTGRES_PASSWORD
              value: mysecretpassword
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: postgresql
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql
          persistentVolumeClaim:
            claimName: postgres-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  labels:
    app: bodhi-main-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---